/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedRestaurantDashboardRouteImport } from './routes/_authed/restaurant/dashboard'
import { Route as AuthedOnboardingOrganizationRouteImport } from './routes/_authed/onboarding/organization'
import { Route as AuthedNgoDashboardRouteImport } from './routes/_authed/ngo/dashboard'
import { Route as AuthedAnimalDashboardRouteImport } from './routes/_authed/animal/dashboard'
import { Route as AuthedAdminOrganizationsRouteImport } from './routes/_authed/admin/organizations'
import { Route as AuthedAdminDashboardRouteImport } from './routes/_authed/admin/dashboard'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRestaurantDashboardRoute =
  AuthedRestaurantDashboardRouteImport.update({
    id: '/restaurant/dashboard',
    path: '/restaurant/dashboard',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOnboardingOrganizationRoute =
  AuthedOnboardingOrganizationRouteImport.update({
    id: '/onboarding/organization',
    path: '/onboarding/organization',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedNgoDashboardRoute = AuthedNgoDashboardRouteImport.update({
  id: '/ngo/dashboard',
  path: '/ngo/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnimalDashboardRoute = AuthedAnimalDashboardRouteImport.update({
  id: '/animal/dashboard',
  path: '/animal/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminOrganizationsRoute =
  AuthedAdminOrganizationsRouteImport.update({
    id: '/admin/organizations',
    path: '/admin/organizations',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminDashboardRoute = AuthedAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/admin/organizations': typeof AuthedAdminOrganizationsRoute
  '/animal/dashboard': typeof AuthedAnimalDashboardRoute
  '/ngo/dashboard': typeof AuthedNgoDashboardRoute
  '/onboarding/organization': typeof AuthedOnboardingOrganizationRoute
  '/restaurant/dashboard': typeof AuthedRestaurantDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/admin/organizations': typeof AuthedAdminOrganizationsRoute
  '/animal/dashboard': typeof AuthedAnimalDashboardRoute
  '/ngo/dashboard': typeof AuthedNgoDashboardRoute
  '/onboarding/organization': typeof AuthedOnboardingOrganizationRoute
  '/restaurant/dashboard': typeof AuthedRestaurantDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/_authed/admin/organizations': typeof AuthedAdminOrganizationsRoute
  '/_authed/animal/dashboard': typeof AuthedAnimalDashboardRoute
  '/_authed/ngo/dashboard': typeof AuthedNgoDashboardRoute
  '/_authed/onboarding/organization': typeof AuthedOnboardingOrganizationRoute
  '/_authed/restaurant/dashboard': typeof AuthedRestaurantDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/organizations'
    | '/animal/dashboard'
    | '/ngo/dashboard'
    | '/onboarding/organization'
    | '/restaurant/dashboard'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/organizations'
    | '/animal/dashboard'
    | '/ngo/dashboard'
    | '/onboarding/organization'
    | '/restaurant/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/admin/dashboard'
    | '/_authed/admin/organizations'
    | '/_authed/animal/dashboard'
    | '/_authed/ngo/dashboard'
    | '/_authed/onboarding/organization'
    | '/_authed/restaurant/dashboard'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/restaurant/dashboard': {
      id: '/_authed/restaurant/dashboard'
      path: '/restaurant/dashboard'
      fullPath: '/restaurant/dashboard'
      preLoaderRoute: typeof AuthedRestaurantDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding/organization': {
      id: '/_authed/onboarding/organization'
      path: '/onboarding/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof AuthedOnboardingOrganizationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ngo/dashboard': {
      id: '/_authed/ngo/dashboard'
      path: '/ngo/dashboard'
      fullPath: '/ngo/dashboard'
      preLoaderRoute: typeof AuthedNgoDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/animal/dashboard': {
      id: '/_authed/animal/dashboard'
      path: '/animal/dashboard'
      fullPath: '/animal/dashboard'
      preLoaderRoute: typeof AuthedAnimalDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/organizations': {
      id: '/_authed/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthedAdminOrganizationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/dashboard': {
      id: '/_authed/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthedAdminDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminDashboardRoute: typeof AuthedAdminDashboardRoute
  AuthedAdminOrganizationsRoute: typeof AuthedAdminOrganizationsRoute
  AuthedAnimalDashboardRoute: typeof AuthedAnimalDashboardRoute
  AuthedNgoDashboardRoute: typeof AuthedNgoDashboardRoute
  AuthedOnboardingOrganizationRoute: typeof AuthedOnboardingOrganizationRoute
  AuthedRestaurantDashboardRoute: typeof AuthedRestaurantDashboardRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminDashboardRoute: AuthedAdminDashboardRoute,
  AuthedAdminOrganizationsRoute: AuthedAdminOrganizationsRoute,
  AuthedAnimalDashboardRoute: AuthedAnimalDashboardRoute,
  AuthedNgoDashboardRoute: AuthedNgoDashboardRoute,
  AuthedOnboardingOrganizationRoute: AuthedOnboardingOrganizationRoute,
  AuthedRestaurantDashboardRoute: AuthedRestaurantDashboardRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
