/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedRestaurantDashboardRouteImport } from './routes/_authed/restaurant/dashboard'
import { Route as AuthedOnboardingOrganizationRouteImport } from './routes/_authed/onboarding/organization'
import { Route as AuthedNgoNearbyFoodRouteImport } from './routes/_authed/ngo/nearby-food'
import { Route as AuthedNgoMyClaimsRouteImport } from './routes/_authed/ngo/my-claims'
import { Route as AuthedNgoDashboardRouteImport } from './routes/_authed/ngo/dashboard'
import { Route as AuthedAnimalNearbyFoodRouteImport } from './routes/_authed/animal/nearby-food'
import { Route as AuthedAnimalMyClaimsRouteImport } from './routes/_authed/animal/my-claims'
import { Route as AuthedAnimalDashboardRouteImport } from './routes/_authed/animal/dashboard'
import { Route as AuthedAdminOrganizationsRouteImport } from './routes/_authed/admin/organizations'
import { Route as AuthedAdminDashboardRouteImport } from './routes/_authed/admin/dashboard'
import { Route as AuthedRestaurantListingsIndexRouteImport } from './routes/_authed/restaurant/listings/index'
import { Route as AuthedRestaurantClaimsIndexRouteImport } from './routes/_authed/restaurant/claims/index'
import { Route as AuthedRestaurantListingsNewRouteImport } from './routes/_authed/restaurant/listings/new'
import { Route as AuthedRestaurantClaimsIdRouteImport } from './routes/_authed/restaurant/claims/$id'
import { Route as AuthedRestaurantListingsIdIndexRouteImport } from './routes/_authed/restaurant/listings/$id/index'
import { Route as AuthedRestaurantListingsIdEditRouteImport } from './routes/_authed/restaurant/listings/$id/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRestaurantDashboardRoute =
  AuthedRestaurantDashboardRouteImport.update({
    id: '/restaurant/dashboard',
    path: '/restaurant/dashboard',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOnboardingOrganizationRoute =
  AuthedOnboardingOrganizationRouteImport.update({
    id: '/onboarding/organization',
    path: '/onboarding/organization',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedNgoNearbyFoodRoute = AuthedNgoNearbyFoodRouteImport.update({
  id: '/ngo/nearby-food',
  path: '/ngo/nearby-food',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNgoMyClaimsRoute = AuthedNgoMyClaimsRouteImport.update({
  id: '/ngo/my-claims',
  path: '/ngo/my-claims',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNgoDashboardRoute = AuthedNgoDashboardRouteImport.update({
  id: '/ngo/dashboard',
  path: '/ngo/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnimalNearbyFoodRoute = AuthedAnimalNearbyFoodRouteImport.update({
  id: '/animal/nearby-food',
  path: '/animal/nearby-food',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnimalMyClaimsRoute = AuthedAnimalMyClaimsRouteImport.update({
  id: '/animal/my-claims',
  path: '/animal/my-claims',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnimalDashboardRoute = AuthedAnimalDashboardRouteImport.update({
  id: '/animal/dashboard',
  path: '/animal/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminOrganizationsRoute =
  AuthedAdminOrganizationsRouteImport.update({
    id: '/admin/organizations',
    path: '/admin/organizations',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminDashboardRoute = AuthedAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRestaurantListingsIndexRoute =
  AuthedRestaurantListingsIndexRouteImport.update({
    id: '/restaurant/listings/',
    path: '/restaurant/listings/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedRestaurantClaimsIndexRoute =
  AuthedRestaurantClaimsIndexRouteImport.update({
    id: '/restaurant/claims/',
    path: '/restaurant/claims/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedRestaurantListingsNewRoute =
  AuthedRestaurantListingsNewRouteImport.update({
    id: '/restaurant/listings/new',
    path: '/restaurant/listings/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedRestaurantClaimsIdRoute =
  AuthedRestaurantClaimsIdRouteImport.update({
    id: '/restaurant/claims/$id',
    path: '/restaurant/claims/$id',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedRestaurantListingsIdIndexRoute =
  AuthedRestaurantListingsIdIndexRouteImport.update({
    id: '/restaurant/listings/$id/',
    path: '/restaurant/listings/$id/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedRestaurantListingsIdEditRoute =
  AuthedRestaurantListingsIdEditRouteImport.update({
    id: '/restaurant/listings/$id/edit',
    path: '/restaurant/listings/$id/edit',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/admin/organizations': typeof AuthedAdminOrganizationsRoute
  '/animal/dashboard': typeof AuthedAnimalDashboardRoute
  '/animal/my-claims': typeof AuthedAnimalMyClaimsRoute
  '/animal/nearby-food': typeof AuthedAnimalNearbyFoodRoute
  '/ngo/dashboard': typeof AuthedNgoDashboardRoute
  '/ngo/my-claims': typeof AuthedNgoMyClaimsRoute
  '/ngo/nearby-food': typeof AuthedNgoNearbyFoodRoute
  '/onboarding/organization': typeof AuthedOnboardingOrganizationRoute
  '/restaurant/dashboard': typeof AuthedRestaurantDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/restaurant/claims/$id': typeof AuthedRestaurantClaimsIdRoute
  '/restaurant/listings/new': typeof AuthedRestaurantListingsNewRoute
  '/restaurant/claims/': typeof AuthedRestaurantClaimsIndexRoute
  '/restaurant/listings/': typeof AuthedRestaurantListingsIndexRoute
  '/restaurant/listings/$id/edit': typeof AuthedRestaurantListingsIdEditRoute
  '/restaurant/listings/$id/': typeof AuthedRestaurantListingsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/admin/organizations': typeof AuthedAdminOrganizationsRoute
  '/animal/dashboard': typeof AuthedAnimalDashboardRoute
  '/animal/my-claims': typeof AuthedAnimalMyClaimsRoute
  '/animal/nearby-food': typeof AuthedAnimalNearbyFoodRoute
  '/ngo/dashboard': typeof AuthedNgoDashboardRoute
  '/ngo/my-claims': typeof AuthedNgoMyClaimsRoute
  '/ngo/nearby-food': typeof AuthedNgoNearbyFoodRoute
  '/onboarding/organization': typeof AuthedOnboardingOrganizationRoute
  '/restaurant/dashboard': typeof AuthedRestaurantDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/restaurant/claims/$id': typeof AuthedRestaurantClaimsIdRoute
  '/restaurant/listings/new': typeof AuthedRestaurantListingsNewRoute
  '/restaurant/claims': typeof AuthedRestaurantClaimsIndexRoute
  '/restaurant/listings': typeof AuthedRestaurantListingsIndexRoute
  '/restaurant/listings/$id/edit': typeof AuthedRestaurantListingsIdEditRoute
  '/restaurant/listings/$id': typeof AuthedRestaurantListingsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/admin/dashboard': typeof AuthedAdminDashboardRoute
  '/_authed/admin/organizations': typeof AuthedAdminOrganizationsRoute
  '/_authed/animal/dashboard': typeof AuthedAnimalDashboardRoute
  '/_authed/animal/my-claims': typeof AuthedAnimalMyClaimsRoute
  '/_authed/animal/nearby-food': typeof AuthedAnimalNearbyFoodRoute
  '/_authed/ngo/dashboard': typeof AuthedNgoDashboardRoute
  '/_authed/ngo/my-claims': typeof AuthedNgoMyClaimsRoute
  '/_authed/ngo/nearby-food': typeof AuthedNgoNearbyFoodRoute
  '/_authed/onboarding/organization': typeof AuthedOnboardingOrganizationRoute
  '/_authed/restaurant/dashboard': typeof AuthedRestaurantDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/restaurant/claims/$id': typeof AuthedRestaurantClaimsIdRoute
  '/_authed/restaurant/listings/new': typeof AuthedRestaurantListingsNewRoute
  '/_authed/restaurant/claims/': typeof AuthedRestaurantClaimsIndexRoute
  '/_authed/restaurant/listings/': typeof AuthedRestaurantListingsIndexRoute
  '/_authed/restaurant/listings/$id/edit': typeof AuthedRestaurantListingsIdEditRoute
  '/_authed/restaurant/listings/$id/': typeof AuthedRestaurantListingsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/organizations'
    | '/animal/dashboard'
    | '/animal/my-claims'
    | '/animal/nearby-food'
    | '/ngo/dashboard'
    | '/ngo/my-claims'
    | '/ngo/nearby-food'
    | '/onboarding/organization'
    | '/restaurant/dashboard'
    | '/api/auth/$'
    | '/restaurant/claims/$id'
    | '/restaurant/listings/new'
    | '/restaurant/claims/'
    | '/restaurant/listings/'
    | '/restaurant/listings/$id/edit'
    | '/restaurant/listings/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/organizations'
    | '/animal/dashboard'
    | '/animal/my-claims'
    | '/animal/nearby-food'
    | '/ngo/dashboard'
    | '/ngo/my-claims'
    | '/ngo/nearby-food'
    | '/onboarding/organization'
    | '/restaurant/dashboard'
    | '/api/auth/$'
    | '/restaurant/claims/$id'
    | '/restaurant/listings/new'
    | '/restaurant/claims'
    | '/restaurant/listings'
    | '/restaurant/listings/$id/edit'
    | '/restaurant/listings/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/admin/dashboard'
    | '/_authed/admin/organizations'
    | '/_authed/animal/dashboard'
    | '/_authed/animal/my-claims'
    | '/_authed/animal/nearby-food'
    | '/_authed/ngo/dashboard'
    | '/_authed/ngo/my-claims'
    | '/_authed/ngo/nearby-food'
    | '/_authed/onboarding/organization'
    | '/_authed/restaurant/dashboard'
    | '/api/auth/$'
    | '/_authed/restaurant/claims/$id'
    | '/_authed/restaurant/listings/new'
    | '/_authed/restaurant/claims/'
    | '/_authed/restaurant/listings/'
    | '/_authed/restaurant/listings/$id/edit'
    | '/_authed/restaurant/listings/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/restaurant/dashboard': {
      id: '/_authed/restaurant/dashboard'
      path: '/restaurant/dashboard'
      fullPath: '/restaurant/dashboard'
      preLoaderRoute: typeof AuthedRestaurantDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding/organization': {
      id: '/_authed/onboarding/organization'
      path: '/onboarding/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof AuthedOnboardingOrganizationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ngo/nearby-food': {
      id: '/_authed/ngo/nearby-food'
      path: '/ngo/nearby-food'
      fullPath: '/ngo/nearby-food'
      preLoaderRoute: typeof AuthedNgoNearbyFoodRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ngo/my-claims': {
      id: '/_authed/ngo/my-claims'
      path: '/ngo/my-claims'
      fullPath: '/ngo/my-claims'
      preLoaderRoute: typeof AuthedNgoMyClaimsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ngo/dashboard': {
      id: '/_authed/ngo/dashboard'
      path: '/ngo/dashboard'
      fullPath: '/ngo/dashboard'
      preLoaderRoute: typeof AuthedNgoDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/animal/nearby-food': {
      id: '/_authed/animal/nearby-food'
      path: '/animal/nearby-food'
      fullPath: '/animal/nearby-food'
      preLoaderRoute: typeof AuthedAnimalNearbyFoodRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/animal/my-claims': {
      id: '/_authed/animal/my-claims'
      path: '/animal/my-claims'
      fullPath: '/animal/my-claims'
      preLoaderRoute: typeof AuthedAnimalMyClaimsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/animal/dashboard': {
      id: '/_authed/animal/dashboard'
      path: '/animal/dashboard'
      fullPath: '/animal/dashboard'
      preLoaderRoute: typeof AuthedAnimalDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/organizations': {
      id: '/_authed/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthedAdminOrganizationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/dashboard': {
      id: '/_authed/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthedAdminDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/restaurant/listings/': {
      id: '/_authed/restaurant/listings/'
      path: '/restaurant/listings'
      fullPath: '/restaurant/listings/'
      preLoaderRoute: typeof AuthedRestaurantListingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/restaurant/claims/': {
      id: '/_authed/restaurant/claims/'
      path: '/restaurant/claims'
      fullPath: '/restaurant/claims/'
      preLoaderRoute: typeof AuthedRestaurantClaimsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/restaurant/listings/new': {
      id: '/_authed/restaurant/listings/new'
      path: '/restaurant/listings/new'
      fullPath: '/restaurant/listings/new'
      preLoaderRoute: typeof AuthedRestaurantListingsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/restaurant/claims/$id': {
      id: '/_authed/restaurant/claims/$id'
      path: '/restaurant/claims/$id'
      fullPath: '/restaurant/claims/$id'
      preLoaderRoute: typeof AuthedRestaurantClaimsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/restaurant/listings/$id/': {
      id: '/_authed/restaurant/listings/$id/'
      path: '/restaurant/listings/$id'
      fullPath: '/restaurant/listings/$id/'
      preLoaderRoute: typeof AuthedRestaurantListingsIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/restaurant/listings/$id/edit': {
      id: '/_authed/restaurant/listings/$id/edit'
      path: '/restaurant/listings/$id/edit'
      fullPath: '/restaurant/listings/$id/edit'
      preLoaderRoute: typeof AuthedRestaurantListingsIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminDashboardRoute: typeof AuthedAdminDashboardRoute
  AuthedAdminOrganizationsRoute: typeof AuthedAdminOrganizationsRoute
  AuthedAnimalDashboardRoute: typeof AuthedAnimalDashboardRoute
  AuthedAnimalMyClaimsRoute: typeof AuthedAnimalMyClaimsRoute
  AuthedAnimalNearbyFoodRoute: typeof AuthedAnimalNearbyFoodRoute
  AuthedNgoDashboardRoute: typeof AuthedNgoDashboardRoute
  AuthedNgoMyClaimsRoute: typeof AuthedNgoMyClaimsRoute
  AuthedNgoNearbyFoodRoute: typeof AuthedNgoNearbyFoodRoute
  AuthedOnboardingOrganizationRoute: typeof AuthedOnboardingOrganizationRoute
  AuthedRestaurantDashboardRoute: typeof AuthedRestaurantDashboardRoute
  AuthedRestaurantClaimsIdRoute: typeof AuthedRestaurantClaimsIdRoute
  AuthedRestaurantListingsNewRoute: typeof AuthedRestaurantListingsNewRoute
  AuthedRestaurantClaimsIndexRoute: typeof AuthedRestaurantClaimsIndexRoute
  AuthedRestaurantListingsIndexRoute: typeof AuthedRestaurantListingsIndexRoute
  AuthedRestaurantListingsIdEditRoute: typeof AuthedRestaurantListingsIdEditRoute
  AuthedRestaurantListingsIdIndexRoute: typeof AuthedRestaurantListingsIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminDashboardRoute: AuthedAdminDashboardRoute,
  AuthedAdminOrganizationsRoute: AuthedAdminOrganizationsRoute,
  AuthedAnimalDashboardRoute: AuthedAnimalDashboardRoute,
  AuthedAnimalMyClaimsRoute: AuthedAnimalMyClaimsRoute,
  AuthedAnimalNearbyFoodRoute: AuthedAnimalNearbyFoodRoute,
  AuthedNgoDashboardRoute: AuthedNgoDashboardRoute,
  AuthedNgoMyClaimsRoute: AuthedNgoMyClaimsRoute,
  AuthedNgoNearbyFoodRoute: AuthedNgoNearbyFoodRoute,
  AuthedOnboardingOrganizationRoute: AuthedOnboardingOrganizationRoute,
  AuthedRestaurantDashboardRoute: AuthedRestaurantDashboardRoute,
  AuthedRestaurantClaimsIdRoute: AuthedRestaurantClaimsIdRoute,
  AuthedRestaurantListingsNewRoute: AuthedRestaurantListingsNewRoute,
  AuthedRestaurantClaimsIndexRoute: AuthedRestaurantClaimsIndexRoute,
  AuthedRestaurantListingsIndexRoute: AuthedRestaurantListingsIndexRoute,
  AuthedRestaurantListingsIdEditRoute: AuthedRestaurantListingsIdEditRoute,
  AuthedRestaurantListingsIdIndexRoute: AuthedRestaurantListingsIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
